<script setup>
import { data as pages } from "../utils/posts.data";
</script>

<template>
  文章列表 — as generated by Posts.vue 组件
  {{ pages[5] }}
  <div class="post-list-container">
    <ul>
      <li v-for="page in pages" :key="page.slug" class="post-card">
        <a :href="`{page.url}`">{{ page.title }}</a><br>
        <span>首次发表：{{ page.date.string }}</span><br>
        <span>最后更新：{{ page.lastUpdated }}</span><br>
        <span>文章摘要：{{ page.excerpt }}</span>
      </li>
    </ul>
  </div>
</template>

<style scoped>

.post-list-container {
  margin: 20px 0;
}
.post-card {
  list-style: none;
  padding: 1em;
  border: 1px solid #ccc;
}
.post-card a {
  margin: 0;
  padding: 0;
  font-size: 1.2em;
}
</style>
