<script setup>
import { data as pages } from "../utils/posts.data.ts";
</script>

<template>
  <h3>文章列表 — as generated by Posts.vue 组件</h3>
  {{ pages }}
  <div v-for="item in pages" :key="item.url" class="post-list-container">
    <ul class="post-card">
      <li>
        <a :href="item.url">{{ item.title }}</a
        ><br />
        <!-- <span>作者： {{ author }}</span> -->
        <span>首次发表： {{ item.date.string }}</span
        ><br />
        <span>最后更新： {{ item.lastUpdated.string }}</span
        ><br />
        <span>摘要： {{ item.excerpt }}</span>
      </li>
    </ul>
  </div>
</template>

<style scoped>

.post-list-container {
  margin: 20px 0;
}
.post-card {
  list-style: none;
  padding: 1em;
  border: 1px solid #ccc;
}
.post-card li a {
  margin: 0;
  padding: 0;
  font-size: 1.5em;
}
</style>
